-- Add all remaining fields from OpsTransaction schema to public.transactions
ALTER TABLE public.transactions 
ADD COLUMN IF NOT EXISTS target_closing_date DATE NULL,
ADD COLUMN IF NOT EXISTS zip TEXT NULL,
ADD COLUMN IF NOT EXISTS price NUMERIC NULL,
ADD COLUMN IF NOT EXISTS list_price NUMERIC NULL,
ADD COLUMN IF NOT EXISTS mls_number TEXT NULL,
ADD COLUMN IF NOT EXISTS listing_date DATE NULL,
ADD COLUMN IF NOT EXISTS expiration_date DATE NULL,
ADD COLUMN IF NOT EXISTS days_on_market INTEGER NULL,
ADD COLUMN IF NOT EXISTS photography_status TEXT NULL,
ADD COLUMN IF NOT EXISTS sign_lockbox_status TEXT NULL,
ADD COLUMN IF NOT EXISTS mls_status TEXT NULL,
ADD COLUMN IF NOT EXISTS open_house_date DATE NULL,
ADD COLUMN IF NOT EXISTS flagged_for_review BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ NULL,
ADD COLUMN IF NOT EXISTS reviewed_by TEXT NULL;
